Version: material::pd::LinearInfluenceFn Class Reference
material::pd::LinearInfluenceFn Class Reference
A class to implement linear influence function.
#include <influenceFn.h>
Public Member Functions
double getInfFn (const double &r) const override
Returns the value of influence function.
double getMoment (const size_t &i) const override
Returns the moment of influence function.
LinearInfluenceFn (const std::vector< double > &params, const size_t &dim)
Constructor.
void print () const override
Prints the information about the instance of the object.
void print (int nt, int lvl) const override
Prints the information about the instance of the object.
std::string printStr (int nt, int lvl) const override
Returns the string containing information about the instance of the object.
Public Member Functions inherited from material::pd::BaseInfluenceFn
BaseInfluenceFn ()=default
Constructor.
Private Attributes
double d_a0
Constants such that J(r) = d_a0 + d_a1 * r.
double d_a1
Constants such that J(r) = d_a0 + d_a1 * r.
Detailed Description
A class to implement linear influence function.
Constructor & Destructor Documentation
LinearInfluenceFn()
material::pd::LinearInfluenceFn::LinearInfluenceFn (const std::vector< double > & params, const size_t & dim) inline
Constructor.
Parameters
params List of parameters
dim Dimension
Member Function Documentation
getInfFn()
double material::pd::LinearInfluenceFn::getInfFn (const double & r) const inline override virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implements material::pd::BaseInfluenceFn.
getMoment()
double material::pd::LinearInfluenceFn::getMoment (const size_t & i) const inline override virtual
Returns the moment of influence function.
If is the influence function for then moment is given by
Parameters
i ith moment
Returns
moment Moment
Implements material::pd::BaseInfluenceFn.
Referenced by printStr().
print() [1/2]
void material::pd::LinearInfluenceFn::print () const inline override virtual
Prints the information about the instance of the object.
Reimplemented from material::pd::BaseInfluenceFn.
Referenced by print().
print() [2/2]
void material::pd::LinearInfluenceFn::print (int nt, int lvl) const inline override virtual
Prints the information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Reimplemented from material::pd::BaseInfluenceFn.
printStr()
std::string material::pd::LinearInfluenceFn::printStr (int nt, int lvl) const inline override virtual
Returns the string containing information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Returns
string String containing information about this object
Reimplemented from material::pd::BaseInfluenceFn.
Referenced by print().
The documentation for this class was generated from the following file:
/root/project/src/material/pd/influenceFn.h