Version: geometry::VolumeCorrection Class Reference
geometry::VolumeCorrection Class Reference
A class to to compute the volume correction for state-based models.
#include <volumeCorrection.h>
Public Member Functions
void print (int nt=0, int lvl=0) const
Prints the information about the instance of the object.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing information about the instance of the object.
VolumeCorrection (data::DataManager *dataManager)
Constructor.
Data Fields
std::vector< std::vector< double > > * d_volumeCorrection_p
Volume correction for the neighborhood of each node.
std::vector< double > * d_weightedVolume_p
Weighted volume of nodes.
Private Member Functions
void correctVolume (const double &horizon, const double &dx, geometry::Neighbor *neighbors, const std::vector< util::Point3 > *nodes)
Computes the volume correction for each node inside the neighborhood. Since nodes close the boundary of the neighborhood have less volume inside the neighborhood and should have less influence while computing the forces.
void weightedVolume (geometry::Neighbor *neighbors, const std::vector< util::Point3 > *nodes, fe::Mesh *p_mesh)
Computes the weighted volume with as the influence function for each discrete node.
Detailed Description
A class to to compute the volume correction for state-based models.
This class implements the so-called volume correction for state-based PD models using the approach described by Silling and implementation details are described by Littlewood.
See also
https://doi.org/10.1007/s10659-007-9125-1
Constructor & Destructor Documentation
VolumeCorrection()
geometry::VolumeCorrection::VolumeCorrection (data::DataManager * dataManager)
Constructor.
Parameters
dataManager Pointer to the data manager object
Member Function Documentation
correctVolume()
void geometry::VolumeCorrection::correctVolume (const double & horizon, const double & dx, geometry::Neighbor * neighbors, const std::vector< util::Point3 > * nodes) private
Computes the volume correction for each node inside the neighborhood. Since nodes close the boundary of the neighborhood have less volume inside the neighborhood and should have less influence while computing the forces.
Parameters
horizon Horizon
dx Nodal spacing
neighbors Class containing the neighborhoods
nodes Pointer to nodal positions
Referenced by VolumeCorrection().
print()
void geometry::VolumeCorrection::print (int nt = 0, int lvl = 0) const inline
Prints the information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
printStr()
std::string geometry::VolumeCorrection::printStr (int nt = 0, int lvl = 0) const
Returns the string containing information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Returns
string String containing information about this object
Referenced by print().
weightedVolume()
void geometry::VolumeCorrection::weightedVolume (geometry::Neighbor * neighbors, const std::vector< util::Point3 > * nodes, fe::Mesh * p_mesh) private
Computes the weighted volume with as the influence function for each discrete node.
Parameters
neighbors Class containing the neighborhoods
nodes Pointer to nodal positions
p_mesh Pointer to the mesh object
Referenced by VolumeCorrection().
The documentation for this class was generated from the following files:
/root/project/src/geometry/volumeCorrection.h
/root/project/src/geometry/volumeCorrection.cpp