Version: data::DataManager Class Reference
data::DataManager Class Reference
Data manager to collect the global simulation data.
#include <DataManager.h>
Public Member Functions
DataManager ()
Constructor.
void print (int nt=0, int lvl=0) const
Prints the information about the instance of the object.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing information about the instance of the object.
Access to the deck objects
void setModelDeckP (inp::ModelDeck *pointer)
inp::ModelDeck * getModelDeckP ()
void setOutputDeckP (inp::OutputDeck *pointer)
inp::OutputDeck * getOutputDeckP ()
Access methods
void setBodyForceP (std::vector< util::Point3 > *pointer)
std::vector< util::Point3 > * getBodyForceP ()
void setForceP (std::vector< util::Point3 > *pointer)
std::vector< util::Point3 > * getForceP ()
void setReactionForceP (std::vector< util::Point3 > *pointer)
std::vector< util::Point3 > * getReactionForceP ()
void setVelocityP (std::vector< util::Point3 > *pointer)
std::vector< util::Point3 > * getVelocityP ()
void setDisplacementP (std::vector< util::Point3 > *pointer)
std::vector< util::Point3 > * getDisplacementP ()
void setMeshP (fe::Mesh *d_mesh_p)
fe::Mesh * getMeshP ()
void setNeighborP (geometry::Neighbor *d_neighbor_p)
geometry::Neighbor * getNeighborP ()
void setVolumeCorrectionP (geometry::VolumeCorrection *pointer)
geometry::VolumeCorrection * getVolumeCorrectionP ()
void setFractureP (geometry::Fracture *pointer)
geometry::InteriorFlags * getInteriorFlagsP ()
void setInteriorFlagsP (geometry::InteriorFlags *pointer)
geometry::Fracture * getFractureP ()
void setStateBasedHelperFunctionsP (util::StateBasedHelperFunctions *pointer)
util::StateBasedHelperFunctions * getStateBasedHelperFunctionsP ()
void setDisplacementLoadingP (loading::ULoading *pointer)
loading::ULoading * getDisplacementLoadingP ()
void setForceLoadingP (loading::FLoading *pointer)
loading::FLoading * getForceLoadingP ()
void setExtensionP (std::vector< std::vector< double > > *pointer)
std::vector< std::vector< double > > * getExtensionP ()
void setStressTensorP (std::vector< util::Matrix33 > *pointer)
std::vector< util::Matrix33 > * getStressTensorP ()
void setStrainTensorP (std::vector< util::Matrix33 > *pointer)
std::vector< util::Matrix33 > * getStrainTensorP ()
void setDilatationP (std::vector< double > *pointer)
std::vector< double > * getDilatationP ()
void setWeightedVolP (std::vector< double > *pointer)
std::vector< double > * getWeightedVolP ()
void setTotalReactionForceP (std::vector< double > *pointer)
std::vector< double > * getTotalReactionForceP ()
void setStrainEnergyP (std::vector< float > *pointer)
std::vector< float > * getStrainEnergyP ()
void setWorkDoneP (std::vector< float > *pointer)
std::vector< float > * getWorkDoneP ()
void setPhiP (std::vector< float > *pointer)
std::vector< float > * getPhiP ()
void setDamageFunctionP (std::vector< float > *pointer)
std::vector< float > * getDamageFunctionP ()
void setBBFractureEnergyP (std::vector< float > *pointer)
std::vector< float > * getBBFractureEnergyP ()
void setFractureEnergyP (std::vector< float > *pointer)
std::vector< float > * getFractureEnergyP ()
void setKineticEnergyP (std::vector< float > *pointer)
std::vector< float > * getKineticEnergyP ()
Private Attributes
Pointers to the deck objects
inp::ModelDeck * d_modelDeck_p = nullptr
Model deck.
inp::OutputDeck * d_outputDeck_p = nullptr
Output deck.
Pointers to the major simulation data
std::vector< util::Point3 > * d_b_p = nullptr
Pointer to the body force vector.
std::vector< util::Point3 > * d_u_p = nullptr
Pointer to the displacement vector.
std::vector< util::Point3 > * d_v_p = nullptr
Pointer to the velocity vector.
std::vector< util::Point3 > * d_f_p = nullptr
Pointer to the force vector.
std::vector< util::Point3 > * d_reaction_force_p = nullptr
Pointer to the reaction force.
std::vector< std::vector< double > > * d_extension_p = nullptr
Extension for the neighborhood of each node.
std::vector< double > * d_dilatation_p = nullptr
Dilatation of nodes.
std::vector< double > * d_weighted_vol_p = nullptr
Weighted volume.
std::vector< double > d_thetaX
Dilation.
std::vector< double > d_mX
Weighted volume.
std::vector< float > * d_e_p = nullptr
Pointer to the strain energy vector.
std::vector< double > * d_total_reaction_force_p = nullptr
Pointer to the total reaction force vector.
std::vector< float > * d_w_p = nullptr
Pointer to the Work done on each of the nodes.
std::vector< float > * d_phi_p = nullptr
Pointer to damage function at the nodes.
std::vector< float > * d_Z_p = nullptr
Pointer to damage function at the nodes.
std::vector< float > * d_eFB_p = nullptr
Pointer to bond-based fracture energy of the nodes.
std::vector< float > * d_eF_p = nullptr
Pointer to fracture energy of the nodes.
std::vector< float > * d_ke_p = nullptr
Pointer to the kinetic energy of the nodes.
std::vector< util::Matrix33 > * d_strain_p = nullptr
Pointer to the strain tensor vector.
std::vector< util::Matrix33 > * d_stress_p = nullptr
Pointer to the stress tensor vector.
fe::Mesh * d_mesh_p = nullptr
Pointer to Mesh object.
geometry::Neighbor * d_neighbor_p = nullptr
Pointer to Neighbor object.
geometry::VolumeCorrection * d_volumeCorrection_p = nullptr
Pointer to Volume Correction object.
geometry::Fracture * d_fracture_p = nullptr
Pointer to Fracture object.
geometry::InteriorFlags * d_interiorFlags_p = nullptr
Pointer to InteriorFlags object.
util::StateBasedHelperFunctions * d_sbhelper_p = nullptr
Pointer to StatebasedHelper function object.
loading::ULoading * d_uLoading_p = nullptr
Pointer to displacement Loading object.
loading::FLoading * d_fLoading_p = nullptr
Pointer to force Loading object.
Detailed Description
Data manager to collect the global simulation data.
Member Function Documentation
getBBFractureEnergyP()
std::vector< float > * data::DataManager::getBBFractureEnergyP ()
Get the pointer to bond-based fracture energy
Returns
pointer
Referenced by model::Output::Output().
getBodyForceP()
std::vector< util::Point3 > * data::DataManager::getBodyForceP ()
Get the pointer to the body force
Returns
pointer
getDamageFunctionP()
std::vector< float > * data::DataManager::getDamageFunctionP ()
Get the pointer to damage function
Returns
pointer
Referenced by model::Output::Output().
getDilatationP()
std::vector< double > * data::DataManager::getDilatationP ()
Get the pointer to dilatation
Returns
pointer
Referenced by util::StateBasedHelperFunctions::dilatation().
getDisplacementLoadingP()
loading::ULoading * data::DataManager::getDisplacementLoadingP ()
Get the pointer to displacement loading object
Returns
pointer
getDisplacementP()
std::vector< util::Point3 > * data::DataManager::getDisplacementP ()
Get the pointer to displacement
Returns
pointer
Referenced by model::Output::Output().
getExtensionP()
std::vector< std::vector< double > > * data::DataManager::getExtensionP ()
Get the pointer to extension state
Returns
pointer
Referenced by util::StateBasedHelperFunctions::StateBasedHelperFunctions().
getForceLoadingP()
loading::FLoading * data::DataManager::getForceLoadingP ()
Get the pointer to force loading object
Returns
pointer
getForceP()
std::vector< util::Point3 > * data::DataManager::getForceP ()
Get the pointer to force
Returns
pointer
Referenced by model::Output::Output().
getFractureEnergyP()
std::vector< float > * data::DataManager::getFractureEnergyP ()
Get the pointer to fracture energy
Returns
pointer
Referenced by model::Output::Output().
getFractureP()
geometry::Fracture * data::DataManager::getFractureP ()
Get the pointer to the mesh object
Returns
pointer
Referenced by model::Output::Output().
getInteriorFlagsP()
geometry::InteriorFlags * data::DataManager::getInteriorFlagsP ()
Get the pointer to volume correction
Returns
pointer
getKineticEnergyP()
std::vector< float > * data::DataManager::getKineticEnergyP ()
Get the pointer to kinetic energy
Returns
pointer
Referenced by model::Output::Output().
getMeshP()
fe::Mesh * data::DataManager::getMeshP ()
Get the pointer to the mesh object
Returns
pointer
Referenced by tools::pp::Compute::Compute(), util::StateBasedHelperFunctions::dilatation(), model::Output::Output(), material::pd::RNPBond::RNPBond(), util::StateBasedHelperFunctions::StateBasedHelperFunctions(), and geometry::VolumeCorrection::VolumeCorrection().
getModelDeckP()
inp::ModelDeck * data::DataManager::getModelDeckP ()
Get the pointer to the model deck
Returns
pointer
Referenced by tools::pp::Compute::Compute(), material::pd::ElasticState::ElasticState(), model::FDModel< T >::FDModel(), material::pd::RNPBond::RNPBond(), util::StateBasedHelperFunctions::StateBasedHelperFunctions(), and geometry::VolumeCorrection::VolumeCorrection().
getNeighborP()
geometry::Neighbor * data::DataManager::getNeighborP ()
Get the pointer to neighborhood object
Returns
pointer
Referenced by model::Output::Output(), and geometry::VolumeCorrection::VolumeCorrection().
getOutputDeckP()
inp::OutputDeck * data::DataManager::getOutputDeckP ()
Get the pointer to the output deck
Returns
pointer
Referenced by material::pd::ElasticState::ElasticState().
getPhiP()
std::vector< float > * data::DataManager::getPhiP ()
Get the pointer to phi
Returns
pointer
Referenced by model::Output::Output().
getReactionForceP()
std::vector< util::Point3 > * data::DataManager::getReactionForceP ()
Get the pointer to reaction force
Returns
pointer
Referenced by model::Output::Output().
getStateBasedHelperFunctionsP()
util::StateBasedHelperFunctions * data::DataManager::getStateBasedHelperFunctionsP ()
Get the pointer to state-nased helper functions
Returns
pointer
Referenced by material::pd::ElasticState::ElasticState().
getStrainEnergyP()
std::vector< float > * data::DataManager::getStrainEnergyP ()
Get the pointer to strain energy
Returns
pointer
Referenced by model::Output::Output().
getStrainTensorP()
std::vector< util::Matrix33 > * data::DataManager::getStrainTensorP ()
Get the pointer to strain tensor
Returns
pointer
Referenced by model::Output::Output().
getStressTensorP()
std::vector< util::Matrix33 > * data::DataManager::getStressTensorP ()
Get the pointer to stress tensor
Returns
pointer
Referenced by model::Output::Output().
getTotalReactionForceP()
std::vector< double > * data::DataManager::getTotalReactionForceP ()
Get the pointer to total reaction force
Returns
pointer
Referenced by model::Output::Output().
getVelocityP()
std::vector< util::Point3 > * data::DataManager::getVelocityP ()
Get the pointer to velocity
Returns
pointer
Referenced by model::Output::Output().
getVolumeCorrectionP()
geometry::VolumeCorrection * data::DataManager::getVolumeCorrectionP ()
Get the pointer to volume correction
Returns
pointer
getWeightedVolP()
std::vector< double > * data::DataManager::getWeightedVolP ()
Get the pointer to weighted volume data
Returns
pointer
getWorkDoneP()
std::vector< float > * data::DataManager::getWorkDoneP ()
Get the pointer to work done
Returns
pointer
Referenced by model::Output::Output().
print()
void data::DataManager::print (int nt = 0, int lvl = 0) const inline
Prints the information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
printStr()
std::string data::DataManager::printStr (int nt = 0, int lvl = 0) const
Returns the string containing information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Returns
string String containing information about this object
Referenced by print().
setBBFractureEnergyP()
void data::DataManager::setBBFractureEnergyP (std::vector< float > * pointer)
Sets the pointer to the bond-based fracture energy
Parameters
pointer Pointer
setBodyForceP()
void data::DataManager::setBodyForceP (std::vector< util::Point3 > * pointer)
Sets the body force pointer
Parameters
pointer Pointer
setDamageFunctionP()
void data::DataManager::setDamageFunctionP (std::vector< float > * pointer)
Sets the pointer to damage function
Parameters
pointer Pointer
setDilatationP()
void data::DataManager::setDilatationP (std::vector< double > * pointer)
Sets the pointer to the dilatation state
Parameters
pointer Pointer
Referenced by util::StateBasedHelperFunctions::dilatation().
setDisplacementLoadingP()
void data::DataManager::setDisplacementLoadingP (loading::ULoading * pointer)
Sets the pointer to the displacement loading object
Parameters
pointer Pointer
setDisplacementP()
void data::DataManager::setDisplacementP (std::vector< util::Point3 > * pointer)
Sets the displacement pointer
Parameters
pointer Pointer
setExtensionP()
void data::DataManager::setExtensionP (std::vector< std::vector< double > > * pointer)
Sets the pointer to the extension state
Parameters
pointer Pointer
Referenced by util::StateBasedHelperFunctions::StateBasedHelperFunctions().
setForceLoadingP()
void data::DataManager::setForceLoadingP (loading::FLoading * pointer)
Sets the pointer to the force loading object
Parameters
pointer Pointer
setForceP()
void data::DataManager::setForceP (std::vector< util::Point3 > * pointer)
Sets the force pointer
Parameters
pointer Pointer
setFractureEnergyP()
void data::DataManager::setFractureEnergyP (std::vector< float > * pointer)
Sets the pointer to the fracture energy
Parameters
pointer Pointer
setFractureP()
void data::DataManager::setFractureP (geometry::Fracture * pointer)
Sets the mesh pointer
Parameters
d_mesh_p Pointer to the mesh object
setInteriorFlagsP()
void data::DataManager::setInteriorFlagsP (geometry::InteriorFlags * pointer)
Sets the mesh pointer
Parameters
d_mesh_p Pointer to the mesh object
setKineticEnergyP()
void data::DataManager::setKineticEnergyP (std::vector< float > * pointer)
Sets the pointer to the kinetic energy
Parameters
pointer Pointer
setMeshP()
void data::DataManager::setMeshP (fe::Mesh * d_mesh_p)
Sets the mesh pointer
Parameters
d_mesh_p Pointer to the mesh object
setModelDeckP()
void data::DataManager::setModelDeckP (inp::ModelDeck * pointer)
Sets the model deck pointer
Parameters
pointer Pointer
Referenced by model::FDModel< T >::FDModel(), and model::QuasiStaticModel< T >::QuasiStaticModel().
setNeighborP()
void data::DataManager::setNeighborP (geometry::Neighbor * d_neighbor_p)
Sets the neighborhood pointer
Parameters
d_neighbor_p Pointer to the neighborhood object
Referenced by tools::pp::Compute::Compute().
setOutputDeckP()
void data::DataManager::setOutputDeckP (inp::OutputDeck * pointer)
Sets the output deck pointer
Parameters
pointer Pointer
Referenced by model::FDModel< T >::FDModel(), and model::QuasiStaticModel< T >::QuasiStaticModel().
setPhiP()
void data::DataManager::setPhiP (std::vector< float > * pointer)
Sets the pointer to the phi vector
Parameters
pointer Pointer
setReactionForceP()
void data::DataManager::setReactionForceP (std::vector< util::Point3 > * pointer)
Sets the body reaction force pointer
Parameters
pointer Pointer
setStateBasedHelperFunctionsP()
void data::DataManager::setStateBasedHelperFunctionsP (util::StateBasedHelperFunctions * pointer)
Sets the pointer to the state-based helper
Parameters
pointer Pointer
Referenced by material::pd::ElasticState::ElasticState().
setStrainEnergyP()
void data::DataManager::setStrainEnergyP (std::vector< float > * pointer)
Sets the pointer to the strain energy
Parameters
pointer Pointer
setStrainTensorP()
void data::DataManager::setStrainTensorP (std::vector< util::Matrix33 > * pointer)
Sets the pointer to the strain tensor
Parameters
pointer Pointer
setStressTensorP()
void data::DataManager::setStressTensorP (std::vector< util::Matrix33 > * pointer)
Sets the pointer to the stress tensor
Parameters
pointer Pointer
setTotalReactionForceP()
void data::DataManager::setTotalReactionForceP (std::vector< double > * pointer)
Sets the pointer to the total reaction force
Parameters
pointer Pointer
setVelocityP()
void data::DataManager::setVelocityP (std::vector< util::Point3 > * pointer)
Sets the velocity pointer
Parameters
pointer Pointer
setVolumeCorrectionP()
void data::DataManager::setVolumeCorrectionP (geometry::VolumeCorrection * pointer)
Sets the volume correction pointer
Parameters
pointer Pointer
setWeightedVolP()
void data::DataManager::setWeightedVolP (std::vector< double > * pointer)
Sets the pointer to the weighted volume data
Parameters
pointer Pointer
setWorkDoneP()
void data::DataManager::setWorkDoneP (std::vector< float > * pointer)
Sets the pointer to the work done vector
Parameters
pointer Pointer
Field Documentation
d_mX
std::vector<double> data::DataManager::d_mX private
Weighted volume.
In case of Regularized state based model, this data is not required
d_thetaX
std::vector<double> data::DataManager::d_thetaX private
Dilation.
In case of Regularized state based model, this will give the spherical (hydrostatic) strain
The documentation for this class was generated from the following files:
/root/project/src/data/DataManager.h
/root/project/src/data/DataManager.cpp