Version: material::pd::GaussianInfluenceFn Class Reference
material::pd::GaussianInfluenceFn Class Reference
A class to implement Gaussian influence function.
#include <influenceFn.h>
Public Member Functions
GaussianInfluenceFn (const std::vector< double > &params, const size_t &dim)
Constructor.
double getInfFn (const double &r) const override
Returns the value of influence function.
double getMoment (const size_t &i) const override
Returns the moment of influence function.
void print () const override
Prints the information about the instance of the object.
void print (int nt, int lvl) const override
Prints the information about the instance of the object.
std::string printStr (int nt, int lvl) const override
Returns the string containing information about the instance of the object.
Public Member Functions inherited from material::pd::BaseInfluenceFn
BaseInfluenceFn ()=default
Constructor.
Private Attributes
double d_alpha
Constants.
double d_beta
Constants.
Detailed Description
A class to implement Gaussian influence function.
Constructor & Destructor Documentation
GaussianInfluenceFn()
material::pd::GaussianInfluenceFn::GaussianInfluenceFn (const std::vector< double > & params, const size_t & dim) inline
Constructor.
Parameters
params List of parameters
dim Dimension
Member Function Documentation
getInfFn()
double material::pd::GaussianInfluenceFn::getInfFn (const double & r) const inline override virtual
Returns the value of influence function.
Parameters
r Reference (initial) bond length
Returns
value Influence function at r
Implements material::pd::BaseInfluenceFn.
getMoment()
double material::pd::GaussianInfluenceFn::getMoment (const size_t & i) const inline override virtual
Returns the moment of influence function.
If is the influence function for then moment is given by
Parameters
i ith moment
Returns
moment Moment
Implements material::pd::BaseInfluenceFn.
Referenced by printStr().
print() [1/2]
void material::pd::GaussianInfluenceFn::print () const inline override virtual
Prints the information about the instance of the object.
Reimplemented from material::pd::BaseInfluenceFn.
Referenced by print().
print() [2/2]
void material::pd::GaussianInfluenceFn::print (int nt, int lvl) const inline override virtual
Prints the information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Reimplemented from material::pd::BaseInfluenceFn.
printStr()
std::string material::pd::GaussianInfluenceFn::printStr (int nt, int lvl) const inline override virtual
Returns the string containing information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Returns
string String containing information about this object
Reimplemented from material::pd::BaseInfluenceFn.
Referenced by print().
The documentation for this class was generated from the following file:
/root/project/src/material/pd/influenceFn.h