Version: rw::writer::Writer Class Reference
rw::writer::Writer Class Reference
A interface class writing data.
#include <writer.h>
Public Member Functions
void close ()
Closes the file and store it to the hard disk.
void open (const std::string &filename, const std::string &format="vtu", const std::string &compress_type="")
Open a .vtu file.
Writer ()
Constructor.
Writer (const std::string &filename, const std::string &format="vtu", const std::string &compress_type="")
Constructor.
~Writer ()
Destructor.
Mesh data
void appendNodes (const std::vector< util::Point3 > *nodes, const std::vector< util::Point3 > *u=nullptr)
Writes the nodes to the file.
void appendMesh (const std::vector< util::Point3 > *nodes, const size_t &element_type, const std::vector< size_t > *en_con, const std::vector< util::Point3 > *u=nullptr)
Writes the mesh data to file.
Point data
void appendPointData (const std::string &name, const std::vector< uint8_t > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< size_t > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< int > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< float > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< double > *data)
Writes the scalar point data to the file.
void appendPointData (const std::string &name, const std::vector< util::Point3 > *data)
Writes the vector point data to the file.
void appendPointData (const std::string &name, const std::vector< util::SymMatrix3 > *data)
Writes the symmetric matrix data associated to nodes to the file.
void appendPointData (const std::string &name, const std::vector< blaze::StaticMatrix< double, 3, 3 > > *data)
Writes the matrix data associated to nodes to the file.
Cell data
void appendCellData (const std::string &name, const std::vector< float > *data)
Writes the float data associated to cells to the file.
void appendCellData (const std::string &name, const std::vector< util::SymMatrix3 > *data)
Writes the symmetric matrix data associated to cells to the file.
Field data
void appendFieldData (const std::string &name, const double &data)
Writes the scalar field data to the file.
void appendFieldData (const std::string &name, const float &data)
Writes the scalar field data to the file.
void addTimeStep (const double &timestep)
Writes the time step to the file.
Crack information
void writeInitialCrack (const std::string &filename, const std::string &compress_type, util::Point3 start, util::Point3 end)
Writes a file with the intital crack visualized as lines.
Private Member Functions
void checkLength (const size_t length, const std::string &name)
Check if the field is not zero This check is important for the legacy vtk writer, since empty fields result in warnings while laoding the data.
Private Attributes
std::string d_format
Format of output file.
rw::writer::LegacyVtkWriter * d_legacyVtkWriter_p
Pointer to the vtk writer class.
rw::writer::MshWriter * d_mshWriter_p
Pointer to the vtk writer class.
rw::writer::VtkWriter * d_vtkWriter_p
Pointer to the vtk writer class.
Detailed Description
A interface class writing data.
This interface separates the caller from vtk library.
Constructor & Destructor Documentation
Writer()
rw::writer::Writer::Writer (const std::string & filename, const std::string & format = "vtu", const std::string & compress_type = "") explicit
Constructor.
Creates and opens .vtu file of name given by filename. The file remains open till the close() function is invoked or if the instance of this class is destroyed.
Parameters
filename Name of file which will be created
format Format of the output file, e.g. "vtu", "msh"
compress_type Specify the compression type (optional)
Member Function Documentation
addTimeStep()
void rw::writer::Writer::addTimeStep (const double & timestep)
Writes the time step to the file.
Parameters
timestep Current time step of the simulation
Referenced by tools::pp::Compute::initWriter().
appendCellData() [1/2]
void rw::writer::Writer::appendCellData (const std::string & name, const std::vector< float > * data)
Writes the float data associated to cells to the file.
Parameters
name Name of the data
data Vector containing the data
appendCellData() [2/2]
void rw::writer::Writer::appendCellData (const std::string & name, const std::vector< util::SymMatrix3 > * data)
Writes the symmetric matrix data associated to cells to the file.
Parameters
name Name of the data
data Vector containing the data
appendFieldData() [1/2]
void rw::writer::Writer::appendFieldData (const std::string & name, const double & data)
Writes the scalar field data to the file.
Parameters
name Name of the data
data Value
appendFieldData() [2/2]
void rw::writer::Writer::appendFieldData (const std::string & name, const float & data)
Writes the scalar field data to the file.
Parameters
name Name of the data
data Value
appendMesh()
void rw::writer::Writer::appendMesh (const std::vector< util::Point3 > * nodes, const size_t & element_type, const std::vector< size_t > * en_con, const std::vector< util::Point3 > * u = nullptr)
Writes the mesh data to file.
Parameters
nodes Vector of nodal coordinates
element_type Type of element
en_con Vector of element-node connectivity
u Vector of nodal displacement
Referenced by tools::pp::Compute::initWriter().
appendNodes()
void rw::writer::Writer::appendNodes (const std::vector< util::Point3 > * nodes, const std::vector< util::Point3 > * u = nullptr)
Writes the nodes to the file.
Parameters
nodes Reference positions of the nodes
u Nodal displacements
Referenced by tools::pp::Compute::initWriter().
appendPointData() [1/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< blaze::StaticMatrix< double, 3, 3 > > * data)
Writes the matrix data associated to nodes to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [2/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< double > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [3/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< float > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [4/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< int > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [5/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< size_t > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [6/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< uint8_t > * data)
Writes the scalar point data to the file.
Parameters
name Name of the data
data Vector containing the data
Referenced by tools::pp::Compute::Compute(), tools::pp::Compute::transformU(), and tools::pp::Compute::transformV().
appendPointData() [7/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< util::Point3 > * data)
Writes the vector point data to the file.
Parameters
name Name of the data
data Vector containing the data
appendPointData() [8/8]
void rw::writer::Writer::appendPointData (const std::string & name, const std::vector< util::SymMatrix3 > * data)
Writes the symmetric matrix data associated to nodes to the file.
Parameters
name Name of the data
data Vector containing the data
checkLength()
void rw::writer::Writer::checkLength (const size_t length, const std::string & name) inline private
Check if the field is not zero This check is important for the legacy vtk writer, since empty fields result in warnings while laoding the data.
Parameters
length Size of the field
name Name of the field
open()
void rw::writer::Writer::open (const std::string & filename, const std::string & format = "vtu", const std::string & compress_type = "")
Open a .vtu file.
Parameters
filename Name of file which will be created
format Format of the output file, e.g. "vtu", "msh"
compress_type Compression type (optional)
Referenced by tools::pp::Compute::initWriter(), and Writer().
writeInitialCrack()
void rw::writer::Writer::writeInitialCrack (const std::string & filename, const std::string & compress_type, util::Point3 start, util::Point3 end)
Writes a file with the intital crack visualized as lines.
Parameters
filename Name of file which will be created
compress_type Compression type (optional)
start First point of the crack
end Last point of the crack
The documentation for this class was generated from the following files:
/root/project/src/rw/writer.h
/root/project/src/rw/writer.cpp