Version: util::compare Namespace Reference
util::compare Namespace Reference
Provides comparison of floating point values
Functions
bool approximatelyEqual (const double &a, const double &b)
Compares if a is approximately equal to b.
bool definitelyGreaterThan (const double &a, const double &b)
Compares if a > to b.
bool definitelyLessThan (const double &a, const double &b)
Compares if a is < to b.
bool essentiallyEqual (const double &a, const double &b)
Compares if a is essentially equal to b.
Detailed Description
Provides comparison of floating point values
Function Documentation
approximatelyEqual()
bool util::compare::approximatelyEqual (const double & a, const double & b)
Compares if a is approximately equal to b.
Parameters
a Value a
b Value b
Returns
Result true if approximately equal else false
Referenced by material::pd::ElasticState::computeParameters().
definitelyGreaterThan()
bool util::compare::definitelyGreaterThan (const double & a, const double & b)
Compares if a > to b.
Parameters
a Value a
b Value b
Returns
Result true if a is definitely greater than b
Referenced by loading::FLoading::apply(), loading::ULoading::apply(), model::FDModel< T >::checkOutputCriteria(), geometry::DampingGeom::computeDampingCoefficient(), material::pd::RNPBond::computeParameters(), material::pd::ElasticState::computeParameters(), model::FDModel< T >::computePostProcFields(), geometry::DataInterior::DataInterior(), tools::pp::Compute::findTipInRects(), loading::FLoading::FLoading(), material::pd::RNPBond::getBondEF(), tools::pp::Compute::getContourContribJInt(), geometry::ComputeInterior::getInteriorFlag(), tools::pp::Compute::getRectsAndNodesForCrackTip(), util::function::hatFunction(), util::geometry::isPointInsideAngledRectangle(), util::geometry::isPointInsideCuboid(), util::geometry::isPointInsideRectangle(), util::geometry::isPointInsideRectangle(), fe::LineElem::mapPointToRefElem(), fe::TetElem::mapPointToRefElem(), fe::TriElem::mapPointToRefElem(), inp::EdgeCrack::ptOutside(), tools::pp::Compute::triCheckAndInterpolateUV(), and loading::ULoading::ULoading().
definitelyLessThan()
bool util::compare::definitelyLessThan (const double & a, const double & b)
Compares if a is < to b.
Parameters
a Value a
b Value b
Returns
Result true if a is definitely less than b
Referenced by geometry::Fracture::addCrack(), fe::Mesh::computeBBox(), geometry::DampingGeom::computeDampingCoefficient(), tools::pp::Compute::computeJIntegral(), fe::Mesh::computeMeshSize(), material::pd::RNPBond::computeParameters(), material::pd::ElasticState::computeParameters(), geometry::DataInterior::DataInterior(), util::function::derLinearStepFunc(), tools::pp::Compute::findNode(), tools::pp::Compute::findTipInRects(), loading::FLoading::FLoading(), tools::pp::Compute::getContourContribJInt(), geometry::ComputeInterior::getInteriorFlag(), tools::pp::Compute::getRectsAndNodesForCrackTip(), util::function::hatFunction(), util::function::hatFunctionQuick(), tools::pp::Compute::interpolateUV(), util::geometry::isPointInsideAngledRectangle(), util::geometry::isPointInsideCuboid(), util::geometry::isPointInsideRectangle(), util::geometry::isPointInsideRectangle(), util::function::linearStepFunc(), fe::LineElem::mapPointToRefElem(), fe::TetElem::mapPointToRefElem(), fe::TriElem::mapPointToRefElem(), inp::EdgeCrack::ptLeftside(), inp::EdgeCrack::ptOutside(), util::function::signVector(), loading::ULoading::ULoading(), tools::mesh::uniformSquare(), tools::mesh::uniformTri(), tools::mesh::uniformTriSym(), and tools::pp::Compute::updateCrack().
essentiallyEqual()
bool util::compare::essentiallyEqual (const double & a, const double & b)
Compares if a is essentially equal to b.
Parameters
a Value a
b Value b
Returns
Result true if essentially equal else false
Referenced by material::pd::ElasticState::dirac_delta().