Version: util::io Namespace Reference
util::io Namespace Reference
Provides geometrical methods such as point inside rectangle.
Functions
std::string getTabS (int nt)
Generate a string contaning nt tabs.
template<class T >
void print (const std::vector< std::vector< T > > &list, int nt=0)
Concatenates the elements of the vector separated with a comma.
template<class T >
void print (const std::vector< T > &list, int nt=0)
Concatenates the elements of the vector separated with a comma and prints them to the standard output stream.
void printBox (const std::pair< std::vector< double >, std::vector< double > > &box, int nt=0)
Prints the corner points of the to the output stream.
void printBox (const std::pair< util::Point3, util::Point3 > &box, int nt=0)
Prints the corner points of the to the output stream.
std::string printBoxStr (const std::pair< std::vector< double >, std::vector< double > > &box, int nt=0)
Prints the corner points of the output stream.
std::string printBoxStr (const std::pair< util::Point3, util::Point3 > &box, int nt=0)
Prints the corner points of the to the output stream.
template<class T >
std::string printStr (const std::vector< std::vector< T > > &list, int nt=0)
Concatenates the elements of the vector separated with a comma.
template<class T >
std::string printStr (const std::vector< T > &list, int nt=0)
Concatenates the elements of the vector separated with a comma.
template<>
std::string printStr (const std::vector< util::Point3 > &list, int nt)
Concatenates the elements of the vector separated with a comma.
Detailed Description
Provides geometrical methods such as point inside rectangle.
Function Documentation
getTabS()
std::string util::io::getTabS (int nt) inline
Generate a string contaning nt tabs.
Parameters
nt Number of tabs
Returns
String containing nt tabs
Referenced by printBoxStr(), printBoxStr(), printStr(), printStr(), printStr(), material::pd::BaseInfluenceFn::printStr(), material::pd::ConstInfluenceFn::printStr(), material::pd::LinearInfluenceFn::printStr(), material::pd::GaussianInfluenceFn::printStr(), data::DataManager::printStr(), fe::BaseElem::printStr(), fe::LineElem::printStr(), fe::MassMatrix::printStr(), fe::Mesh::printStr(), fe::QuadData::printStr(), fe::QuadElem::printStr(), fe::TetElem::printStr(), fe::TriElem::printStr(), geometry::DampingGeom::printStr(), geometry::Fracture::printStr(), geometry::BaseInterior::printStr(), geometry::ComputeInterior::printStr(), geometry::DataInterior::printStr(), geometry::InteriorFlags::printStr(), geometry::Neighbor::printStr(), geometry::VolumeCorrection::printStr(), inp::DampingGeomData::printStr(), inp::AbsorbingCondDeck::printStr(), inp::EdgeCrack::printStr(), inp::FractureDeck::printStr(), inp::ICData::printStr(), inp::InitialConditionDeck::printStr(), inp::InteriorFlagsDeck::printStr(), inp::BCData::printStr(), inp::LoadingDeck::printStr(), inp::MassMatrixDeck::printStr(), inp::MatData::printStr(), inp::MaterialDeck::printStr(), inp::MeshDeck::printStr(), inp::ModelDeck::printStr(), inp::NeighborDeck::printStr(), inp::OutputDeck::printStr(), inp::PolicyDeck::printStr(), inp::QuadratureDeck::printStr(), inp::RestartDeck::printStr(), inp::SolverDeck::printStr(), inp::Input::printStr(), loading::FLoading::printStr(), loading::InitialCondition::printStr(), and loading::ULoading::printStr().
print() [1/2]
template<class T > void util::io::print (const std::vector< std::vector< T > > & list, int nt = 0) inline
Concatenates the elements of the vector separated with a comma.
Parameters
list The vector with the elements
nt Number of tabs prepend to the concatenated vector
print() [2/2]
template<class T > void util::io::print (const std::vector< T > & list, int nt = 0) inline
Concatenates the elements of the vector separated with a comma and prints them to the standard output stream.
Parameters
list The vector with the elements
nt Number of tabs prepend to the concatenated vector
printBox() [1/2]
void util::io::printBox (const std::pair< std::vector< double >, std::vector< double > > & box, int nt = 0) inline
Prints the corner points of the to the output stream.
Parameters
box Corner point of the box
nt Number of tabs at the beginning of the string
printBox() [2/2]
void util::io::printBox (const std::pair< util::Point3, util::Point3 > & box, int nt = 0) inline
Prints the corner points of the to the output stream.
Parameters
box Corner point of the box
nt Number of tabs at the beginning of the string
printBoxStr() [1/2]
std::string util::io::printBoxStr (const std::pair< std::vector< double >, std::vector< double > > & box, int nt = 0) inline
Prints the corner points of the output stream.
Parameters
box Corner point of the box
nt Number of tabs at the beginning of the string
Returns
Resulting string
printBoxStr() [2/2]
std::string util::io::printBoxStr (const std::pair< util::Point3, util::Point3 > & box, int nt = 0) inline
Prints the corner points of the to the output stream.
Parameters
box Corner point of the box
nt Number of tabs at the beginning of the string
Returns
Resulting string
Referenced by printBox(), printBox(), fe::Mesh::printStr(), geometry::BaseInterior::printStr(), geometry::ComputeInterior::printStr(), and geometry::DataInterior::printStr().
printStr() [1/3]
template<class T > std::string util::io::printStr (const std::vector< std::vector< T > > & list, int nt = 0) inline
Concatenates the elements of the vector separated with a comma.
Parameters
list The vector with the elements
nt Number of tabs prepend to the concatenated vector
Returns
Resulting string
printStr() [2/3]
template<class T > std::string util::io::printStr (const std::vector< T > & list, int nt = 0) inline
Concatenates the elements of the vector separated with a comma.
Parameters
list The vector with the elements
nt Number of tabs prepend to the concatenated vector
Returns
Resulting string
Referenced by fe::Mesh::computeVol(), print(), print(), fe::QuadData::printStr(), inp::BCData::printStr(), inp::OutputDeck::printStr(), and test::testTetElem().
printStr() [3/3]
template<> std::string util::io::printStr (const std::vector< util::Point3 > & list, int nt) inline
Concatenates the elements of the vector separated with a comma.
Parameters
list The vector with the elements
nt NUmber of tabs prepend to the concatenated vector
Returns
Resulting string