Version: tools::mesh Namespace Reference
tools::mesh Namespace Reference
Namespace for simple mesh generation.
Functions
void fe1D (const std::string &filename)
Generate uniform mesh in 1-d and writes the data to files specified in input filename.
void fe2D (const std::string &filename)
Generates uniform mesh in 2-d and writes the data to files specified in input filename.
void uniformSquare (const std::string &filename)
Generates uniform square mesh in 2-d and writes the data to files specified in input filename.
void uniformTri (const std::string &filename)
Generates uniform triangular mesh in 2-d and writes the data to files specified in input filename.
void uniformTriSym (const std::string &filename)
Generates uniform symmetric triangular mesh in 2-d and writes the data to files specified in input filename.
Detailed Description
Namespace for simple mesh generation.
In this namespace we define the methods for generating simple finite element/finite difference mesh in 1-d and 2-d. For finite element, we can specify three types of triangular mesh which differ in how we create triangle on uniform grid.
Function Documentation
fe1D()
void tools::mesh::fe1D (const std::string & filename)
Generate uniform mesh in 1-d and writes the data to files specified in input filename.
Parameters
filename Name of YAML input file
fe2D()
void tools::mesh::fe2D (const std::string & filename)
Generates uniform mesh in 2-d and writes the data to files specified in input filename.
Parameters
filename Name of YAML input file
uniformSquare()
void tools::mesh::uniformSquare (const std::string & filename)
Generates uniform square mesh in 2-d and writes the data to files specified in input filename.
Parameters
filename Name of YAML input file
Referenced by fe2D().
uniformTri()
void tools::mesh::uniformTri (const std::string & filename)
Generates uniform triangular mesh in 2-d and writes the data to files specified in input filename.
Parameters
filename Name of YAML input file
Referenced by fe2D().
uniformTriSym()
void tools::mesh::uniformTriSym (const std::string & filename)
Generates uniform symmetric triangular mesh in 2-d and writes the data to files specified in input filename.
Parameters
filename Name of YAML input file
Referenced by fe2D().