Version: util::function Namespace Reference
util::function Namespace Reference
Provides geometrical methods such as point inside rectangle.
Functions
double derLinearStepFunc (const double &x, const double &x1, const double &x2)
Compute derivative of linear step function.
double doubleGaussian2d (const util::Point3 &x, const size_t &dof, const std::vector< double > &params)
Compute sum of two Gaussian function in 2-d.
double gaussian (const double &r, const double &a, const double &beta)
Compute Gaussian function in 1-d.
double gaussian2d (const util::Point3 &x, const size_t &dof, const std::vector< double > &params)
Compute Gaussian function in 2-d.
double getDeterminant (const std::vector< util::Point3 > &rows)
Get determinant of 3-d matrix.
double hatFunction (const double &x, const double &x_min, const double &x_max)
Computes hat function at given point.
double hatFunctionQuick (const double &x, const double &x_min, const double &x_max)
Computes hat function at given point.
double linearStepFunc (const double &x, const double &x1, const double &x2)
Compute linear step function.
util::Point3 signVector (const util::Point3 &v)
Get vector with plus or minus 1 depending on the sign of component of another vector.
Detailed Description
Provides geometrical methods such as point inside rectangle.
Function Documentation
derLinearStepFunc()
double util::function::derLinearStepFunc (const double & x, const double & x1, const double & x2)
Compute derivative of linear step function.
Parameters
x Point in real line
x1 Point such that function is linear with slope 1 in [0, x1)
x2 Point such that function is constant in [x1, x1 + x2)
Returns
value Derivative of step function at x
Referenced by loading::ULoading::apply().
doubleGaussian2d()
double util::function::doubleGaussian2d (const util::Point3 & x, const size_t & dof, const std::vector< double > & params)
Compute sum of two Gaussian function in 2-d.
Double Gaussian (2-d) function:
where and are two Gaussian 2-d function as described in Gaussian2d() with different values of .
Parameters
x Coordinates of point
params List of parameters
dof Component of Gaussian function
Returns
value Component of Gaussian 2-d vector function along dof
Referenced by loading::InitialCondition::getICFormula().
gaussian()
double util::function::gaussian (const double & r, const double & a, const double & beta)
Compute Gaussian function in 1-d.
Gaussian (1-d) function:
Here is the amplitude and is the exponential factor.
Parameters
r Distance from origin
a Amplitude
beta Factor in exponential function
Returns
value Component of Gaussian 1-d function
Referenced by doubleGaussian2d(), and gaussian2d().
gaussian2d()
double util::function::gaussian2d (const util::Point3 & x, const size_t & dof, const std::vector< double > & params)
Compute Gaussian function in 2-d.
Gaussian (2-d) function:
where
Here is the center of the pulse, is the amplitude, is the exponential factor, and is the direction of the pulse.
Parameters
x Coordinates of point
params List of parameters
dof Component of Gaussian function
Returns
value Component of Gaussian 2-d vector function along dof
Referenced by loading::InitialCondition::getICFormula().
getDeterminant()
double util::function::getDeterminant (const std::vector< util::Point3 > & rows)
Get determinant of 3-d matrix.
Parameters
rows Three rows of matrix
Returns
det Determinant
Referenced by util::geometry::getTetVolume().
hatFunction()
double util::function::hatFunction (const double & x, const double & x_min, const double & x_max)
Computes hat function at given point.
Hat function: f ^ | | 1 o | /|\ | / | \ | / | \ | / | \ | / | \ | / | \ o____________o____________o______\ x / x_min x_max
Parameters
x Point in real line
x_min Left side point in real line
x_max Right side point in real line
Returns
value Evaluation of hat function at x
Referenced by loading::FLoading::apply().
hatFunctionQuick()
double util::function::hatFunctionQuick (const double & x, const double & x_min, const double & x_max)
Computes hat function at given point.
This version does not test if point x is in valid interval.
Hat function: f ^ | | 1 o | /|\ | / | \ | / | \ | / | \ | / | \ | / | \ o____________o____________o______\ x / x_min x_max
Parameters
x Point in real line
x_min Left side point in real line
x_max Right side point in real line
Returns
value Evaluation of hat function at x
linearStepFunc()
double util::function::linearStepFunc (const double & x, const double & x1, const double & x2)
Compute linear step function.
Step function:
f ^ | __________ | / | / | _______/ | / | / |/_________________________ t x1 x1+x2
Linear (with slope 1) in [0,l1), constant in [l1,l1+l2)
Periodic with periodicity l1+l2
Parameters
x Point in real line
x1 Point such that function is linear with slope 1 in [0, x1)
x2 Point such that function is constant in [x1, x1 + x2)
Returns
value Evaluation of step function at x
Referenced by loading::FLoading::apply(), and loading::ULoading::apply().
signVector()
util::Point3 util::function::signVector (const util::Point3 & v)
Get vector with plus or minus 1 depending on the sign of component of another vector.
Parameters
v Vector from which a new vector is created
Returns
vec Vector