Version: test Namespace Reference
test Namespace Reference
Namespace to group the methods used in testing of the library.
Functions
double getExactIntegrationRefQuad (size_t alpha, size_t beta)
Computes integration of polynomial exactly over reference quadrangle.
double getExactIntegrationRefTet (size_t alpha, size_t beta, size_t theta)
Computes integration of polynomial exactly over reference tetrahedral.
double getExactIntegrationRefTri (size_t alpha, size_t beta)
Computes integration of polynomial exactly over reference triangle.
double getNChooseR (size_t n, size_t r)
Computes "n choose r".
void testFracture ()
Perform test on Fracture class and check if bit-wise functions are working correctly.
void testLineElem (size_t n)
Perform test on quadrature points on line elements.
void testQuadElem (size_t n)
Perform test on quadrature points on quadrangle elements.
void testTetElem (size_t n)
Perform test on quadrature points on tetrahedral elements.
void testTriElem (size_t n)
Perform test on quadrature points on triangle elements.
void testTriElemTime (size_t n, size_t N)
Computes the time needed when quad data for elements are stored and when they are computed as and when needed.
Detailed Description
Namespace to group the methods used in testing of the library.
Function Documentation
getExactIntegrationRefQuad()
double test::getExactIntegrationRefQuad (size_t alpha, size_t beta)
Computes integration of polynomial exactly over reference quadrangle.
Given , the exact integration is given by
If either or are odd number then . Otherwise, .
Parameters
alpha Polynomial order in variable s
beta Polynomial order in variable t
Returns
I Exact integration of
Referenced by testQuadElem().
getExactIntegrationRefTet()
double test::getExactIntegrationRefTet (size_t alpha, size_t beta, size_t theta)
Computes integration of polynomial exactly over reference tetrahedral.
Parameters
alpha Polynomial order in variable s
beta Polynomial order in variable t
theta Polynomial order in variable r
Returns
I Exact integration of
Referenced by testTetElem().
getExactIntegrationRefTri()
double test::getExactIntegrationRefTri (size_t alpha, size_t beta)
Computes integration of polynomial exactly over reference triangle.
Given , the exact integration is given by
where
We have so that term for is not zero. Above formula gives the exact value of integral of over reference triangle.
Parameters
alpha Polynomial order in variable s
beta Polynomial order in variable t
Returns
I Exact integration of
Referenced by testTriElem().
getNChooseR()
double test::getNChooseR (size_t n, size_t r)
Computes "n choose r".
Computes formula
Parameters
n Number
r Number which is smaller or equal to n
Returns
Value Value of "n choose r"
Referenced by getExactIntegrationRefTet(), and getExactIntegrationRefTri().
testLineElem()
void test::testLineElem (size_t n)
Perform test on quadrature points on line elements.
This function performs accuracy test of the quadrature points for integration over reference line with vertices at {-1, 1}. List of tests are as follows:
Computes quadrature points of the given order, writes them to the file, and checks if the sum of quadrature weights is equal to 0.5 (area of reference triangle).
Also tests the exactness of the integration of the polynomial up to given order. Suppose is the order of quadrature point, then we test if the integration of the function is exact for and such that . The exact integration of function over reference triangle is
where
We have so that term for is not zero. Above formula gives the exact value of integral of over reference triangle. Approximation by quadrature point is as follows
where is the total number of quad points, and are the quad weight and point. In this test, we compare and and report problem if both do not match.
Test the accuracy for simple quadrangle mesh on square domain [0,1]^2. Exact integration of polynomial on is given by
We compare above with the approximation computed from the quadrature points. We consider where is the order of approximation we are testing.
Parameters
n Order of quadrature point approximation
Todo:
Implement this method!
testQuadElem()
void test::testQuadElem (size_t n)
Perform test on quadrature points on quadrangle elements.
This function performs accuracy test of the quadrature points for integration over reference triangle with vertices at {(0,0), (1,0), (0,1)}. List of tests are as follows:
Computes quadrature points of the given order, writes them to the file, and checks if the sum of quadrature weights is equal to 2, i.e. area of reference quadrangle element.
Also tests the exactness of the integration of the polynomial up to given order. Suppose is the order of quadrature point, then we test if the integration of the function is exact for and such that . The exact integration of function over reference triangle is
where
We have so that term for is not zero. Above formula gives the exact value of integral of over reference triangle. Approximation by quadrature point is as follows
where is the total number of quad points, and are the quad weight and point. In this test, we compare and and report problem if both do not match.
Test the accuracy for simple quadrangle mesh on square domain [0,1]^2. Exact integration of polynomial on is given by
We compare above with the approximation computed from the quadrature points. We consider where is the order of approximation we are testing.
Parameters
n Order of quadrature point approximation
testTetElem()
void test::testTetElem (size_t n)
Perform test on quadrature points on tetrahedral elements.
Parameters
n Order of quadrature point approximation
testTriElem()
void test::testTriElem (size_t n)
Perform test on quadrature points on triangle elements.
This function performs accuracy test of the quadrature points for integration over reference triangle with vertices at {(0,0), (1,0), (0,1)}. List of tests are as follows:
Computes quadrature points of the given order, writes them to the file, and checks if the sum of quadrature weights is equal to 0.5, i.e. area of reference triangle.
Also tests the exactness of the integration of the polynomial up to given order. Suppose is the order of quadrature point, then we test if the integration of the function is exact for and such that . The exact integration of function over reference triangle is
where
We have so that term for is not zero. Above formula gives the exact value of integral of over reference triangle. Approximation by quadrature point is as follows
where is the total number of quad points, and are the quad weight and point. In this test, we compare and and report problem if both do not match.
Test the accuracy for simple triangular mesh on square domain [0,1]^2. Exact integration of polynomial on is given by
We compare above with the approximation computed from the quadrature points. We consider where is the order of approximation we are testing.
Parameters
n Order of quadrature point approximation
testTriElemTime()
void test::testTriElemTime (size_t n, size_t N)
Computes the time needed when quad data for elements are stored and when they are computed as and when needed.
This function allocates dummy elements and test how much time it is required to do computation when the quad data are stored for each element and when the quad data are computed.
Parameters
n Order of quadrature point approximation
N Number of elements on which this test is performed