Version: util::transformation Namespace Reference
util::transformation Namespace Reference
Provides geometrical methods such rotation of a vector.
Functions
std::vector< size_t > cyclicOrderACW (const size_t &i, const size_t &j, const size_t &k, const size_t &n)
Returns the list of elements in anti-clockwise order with indices i, j, and k as the first three elements.
std::vector< size_t > cyclicOrderACW (const size_t &i, const size_t &j, const size_t &n)
Returns the list of elements in anti-clockwise order starting from given index i and then index j.
std::vector< size_t > cyclicOrderACW (const size_t &i, const size_t &n)
Returns the list of elements in anti-clockwise order starting from given index i.
std::vector< double > rotateACW2D (const std::vector< double > &x, const double &theta)
Rotates a vector in xy-plane in anti-clockwise direction.
util::Point3 rotateACW2D (const util::Point3 &x, const double &theta)
Rotates a vector in xy-plane in anti-clockwise direction.
std::vector< double > rotateCW2D (const std::vector< double > &x, const double &theta)
Rotates a vector in xy-plane in clockwise direction.
util::Point3 rotateCW2D (const util::Point3 &x, const double &theta)
Rotates a vector in xy-plane in clockwise direction.
Detailed Description
Provides geometrical methods such rotation of a vector.
Function Documentation
cyclicOrderACW() [1/3]
std::vector< size_t > util::transformation::cyclicOrderACW (const size_t & i, const size_t & j, const size_t & k, const size_t & n)
Returns the list of elements in anti-clockwise order with indices i, j, and k as the first three elements.
Parameters
i Index i which will be the first element of returned list
j Index j which will be the second element of returned list
k Index k which will be the third element of returned list
n Number of elements
Returns
list List of indices starting from i, j and k in ACW order
cyclicOrderACW() [2/3]
std::vector< size_t > util::transformation::cyclicOrderACW (const size_t & i, const size_t & j, const size_t & n)
Returns the list of elements in anti-clockwise order starting from given index i and then index j.
Parameters
i Index i which will be the first element of returned list
j Index j which will be the second element of returned list
n Number of elements
Returns
list List of indices starting from i and j in ACW order
cyclicOrderACW() [3/3]
std::vector< size_t > util::transformation::cyclicOrderACW (const size_t & i, const size_t & n)
Returns the list of elements in anti-clockwise order starting from given index i.
Parameters
i Index i which will be the first element of returned list
n Number of elements
Returns
list List of indices starting from i in ACW order
rotateACW2D() [1/2]
std::vector< double > util::transformation::rotateACW2D (const std::vector< double > & x, const double & theta)
Rotates a vector in xy-plane in anti-clockwise direction.
Parameters
x Point
theta Angle
Returns
Point after rotation
rotateACW2D() [2/2]
util::Point3 util::transformation::rotateACW2D (const util::Point3 & x, const double & theta)
Rotates a vector in xy-plane in anti-clockwise direction.
Parameters
x Point
theta Angle
Returns
Point after rotation
rotateCW2D() [1/2]
std::vector< double > util::transformation::rotateCW2D (const std::vector< double > & x, const double & theta)
Rotates a vector in xy-plane in clockwise direction.
Parameters
x Point
theta Angle
Returns
Point after rotation
Referenced by util::geometry::isPointInsideAngledRectangle(), inp::EdgeCrack::ptOutside(), rotateACW2D(), and rotateACW2D().
rotateCW2D() [2/2]
util::Point3 util::transformation::rotateCW2D (const util::Point3 & x, const double & theta)
Rotates a vector in xy-plane in clockwise direction.
Parameters
x Point
theta Angle
Returns
Point after rotation