Version: inp::EdgeCrack Struct Reference
inp::EdgeCrack Struct Reference
A structure to edge crack of any orientation.
#include <fractureDeck.h>
Public Member Functions
EdgeCrack ()
Constructor.
void print (int nt=0, int lvl=0) const
Prints the information about the instance of the object.
std::string printStr (int nt=0, int lvl=0) const
Returns the string containing information about the instance of the object.
bool ptLeftside (util::Point3 p, util::Point3 pb, util::Point3 pt)
Checks if point lies on left(top) or right(bottom) of crack.
bool ptOutside (util::Point3 p, int o, util::Point3 pb, util::Point3 pt, double theta=0.0)
Checks if point lies outside the crack.
bool ptRightside (util::Point3 p, util::Point3 pb, util::Point3 pt)
Checks if point lies on left(top) or right(bottom) of crack.
Data Fields
double d_activationTime
Activation time (for example when we abruptly slit the domain at specified time)
bool d_crackAcrivated
Is crack activated.
int d_ib
Closest id of node to bottom (left) crack tip.
util::Point3 d_initPb
Bottom (left) crack tip location (initial)
util::Point3 d_initPt
Top (right) crack tip location (initial)
int d_it
Closest id of node to top (right) crack tip.
double d_l
Total current length of crack.
double d_lb
Current length of crack on bottom side (left side)
double d_lt
Current length of crack on top side (right side)
int d_o
Orientation of crack.
util::Point3 d_oldPb
Bottom (left) crack tip location (old)
util::Point3 d_oldPt
Top (right) crack tip location (old)
util::Point3 d_pb
Bottom (left) crack tip location.
util::Point3 d_pt
Top (right) crack tip location.
double d_theta
Angle the edge crack makes with the horizontal axis.
bool d_trackb
Track bottom point (left) of crack.
bool d_trackt
Track top point (right) of crack.
util::Point3 d_vb
Velocity of bottom (left) crack tip.
util::Point3 d_vt
Velocity of top (right) crack tip.
Detailed Description
A structure to edge crack of any orientation.
Member Function Documentation
print()
void inp::EdgeCrack::print (int nt = 0, int lvl = 0) const inline
Prints the information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
printStr()
std::string inp::EdgeCrack::printStr (int nt = 0, int lvl = 0) const inline
Returns the string containing information about the instance of the object.
Parameters
nt Number of tabs to append before each line of string
lvl Level of information sought (higher level means more information)
Returns
string String containing information about this object
Referenced by print().
ptLeftside()
bool inp::EdgeCrack::ptLeftside (util::Point3 p, util::Point3 pb, util::Point3 pt) inline
Checks if point lies on left(top) or right(bottom) of crack.
Parameters
p Point p to check
pb Bottom (left) point of crack line
pt Top (right) point of crack line
Returns
true if lies on left(top)
Referenced by geometry::Fracture::computeFracturedBondFd(), and ptRightside().
ptOutside()
bool inp::EdgeCrack::ptOutside (util::Point3 p, int o, util::Point3 pb, util::Point3 pt, double theta = 0.0) inline
Checks if point lies outside the crack.
Parameters
p Point p to check
o Orientation of crack
pb Bottom (left) point of crack line
pt Top (right) point of crack line
theta Angle that crack line makes with horizontal axis
Returns
true if lies outside
Referenced by geometry::Fracture::computeFracturedBondFd().
ptRightside()
bool inp::EdgeCrack::ptRightside (util::Point3 p, util::Point3 pb, util::Point3 pt) inline
Checks if point lies on left(top) or right(bottom) of crack.
Parameters
p Point p to check
pb Bottom (left) point of crack line
pt Top (right) point of crack line
Returns
true if lies on right(bottom)
Referenced by geometry::Fracture::computeFracturedBondFd().
Field Documentation
d_o
int inp::EdgeCrack::d_o
Orientation of crack.
1 for orientation along horizontal axis (x-axis),
-1 for orientation along vertical axis (y-axis),
0 for any crack which makes nonzero angle with the horizontal axis
Referenced by geometry::Fracture::computeFracturedBondFd(), tools::pp::Compute::findTipInRects(), tools::pp::Compute::getRectsAndNodesForCrackTip(), printStr(), and inp::Input::setFractureDeck().
d_theta
double inp::EdgeCrack::d_theta
Angle the edge crack makes with the horizontal axis.
0 if orientation = 1,
if orientation = -1
Value for orientation = 0
Referenced by printStr(), and inp::Input::setFractureDeck().
The documentation for this struct was generated from the following file:
/root/project/src/inp/decks/fractureDeck.h